const routes = {
    home: '/',
    search: '/search',
    playlist: '/playlist',
    album: '/album',
    song: '/song',
    artist: '/artist',
    podcast: '/podcast',
    genre: '/genre',
    concerts: '/concerts',
    signup: '/signup',
    login: '/login',
    user: '/user',
    likedSongs: '/likedSongs',
    settings: '/settings',
    premium: '/premium',
    premium_register: '/premium/register',
    detailSong: '/song',
    mvSong: '/video',

    admin_dashboard: '/admin/dashboard',
    admin_user: '/admin/account/list_users',
    admin_artist: '/admin/account/list_artists',
    admin_album: '/admin/list_albums',
    admin_song: '/admin/list_songs',
    admin_playlist: '/admin/list_playlists',
    admin_premium: '/admin/list_premium',
    admin_premium_register: '/admin/list_premium_register',
    admin_genre: '/admin/list_genres',

    artist_dashboard: '/artist/dashboard',
    artist_song: '/artist/list_songs',
    artist_album: '/artist/list_albums',
    artist_playlist: '/artist/list_playlists',
    artist_create_album: '/artist/create/album',
    artist_create_song: '/artist/create/song',
    artist_listens: '/artist/listens',
    artist_turnover: '/artist/turn_over',
    
    chat: '/chat',
    category: '/category',
    searchSongAlbumArt: '/searchSongAlbumArt',

};

export default routes;
